"""Added account table

Revision ID: 87fd6a5d5c80
Revises: be533395d7b3
Create Date: 2023-04-25 11:51:12.059887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fd6a5d5c80'
down_revision = 'be533395d7b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
